python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_4_0_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_4_1_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_4_2_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_4_3_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
