python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_6_4_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_6_5_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_6_6_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_6_7_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
