python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_5_4_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_5_5_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_5_6_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
python /Users/cerusu/GITHUB/zMstarPDF/python/catalogue_utilities/photozMillennium.py GGL_los_8_5_7_N_4096_ang_4_Henriques2014_galaxi_griz.images.txt
